### ISSUE TITLE
CLI coloring is broken since VS Code 1.69.1

### ISSUE THREAD

**Issue by FloMaile** [betwo/vscode-catkin-tools#45] opened 2022-07-13 15:30 UTC
```
[1m[31mErrors[0m    [31m <<[0m [36mXXXXXX[0m:[34mmake[0m [1m[31m/home/XXXXX/ros_ws/logs/XXXXX/build.make.004.log[0m[0m
[31m...............................................................................[0m[0m
[1m[31mFailed[0m    [31m <<[0m [36mXXXXXXXX[0m:[34mmake                   [0m[ [33mExited with code [1m[33m2[0m ][0m   
```

`XXXXXXX` is just to black out the names.

**Comment by betwo** [comment] 2022-07-14 11:11
Thank you for reporting this!
As mentioned in #46, this might not be an issue of the vs code version, but the latest extension release.
I'll try to reproduce this asap.

**Comment by betwo** [comment] 2022-07-14 12:52
From what I have found so far, the missing colors are due to us switching to [Pseudoterminal](https://code.visualstudio.com/api/references/vscode-api#Pseudoterminal).

Will try to find a way to bring back the colors.

**Comment by FloMaile** [comment] 2022-08-05 16:21
Any updates on this so far? Would be nice to get the colors back :)

**Comment by betwo** [comment] 2022-08-05 19:51
Sorry about all the delay, I have been really busy the last weeks.
Tomorrow I'll hopefully be able to cleanup my local fixes and release them,

**Comment by betwo** [comment] 2022-08-09 00:32
I just released `4.3.0-prelease`, which should have full color support again and should also improve test handling in general.
Could you please take a look if the color issues you have are fixed with that?

**Comment by FloMaile** [comment] 2022-08-09 10:05
Currently VSC only published version 4.2.0. Thank you for the effort!

**Comment by betwo** [comment] 2022-08-09 16:38
You should be able to switch to the pre-release version in vscode.
Just go to the extensions tab and select the catkin tools extension. There should be a button for switching to the pre-release.
Does that work?

**Comment by FloMaile** [comment] 2022-08-10 07:39
I can confirm that the color support works again. Tests are still not working properly.

**Comment by betwo** [comment] 2022-08-10 19:19
Thanks for the confirmation. Let's close this issue then and continue the discussion on issue #46 .

**Closed as completed by betwo** 2022-08-10 19:19 UTC
Labels: bug
