### ISSUE TITLE
merge compile_commands.json not outputting

### ISSUE THREAD

**Issue by SubaruArai** [betwo/vscode-catkin-tools#43] opened 2022-02-14 04:05 UTC
First of all thank you for this great extension!

## The issue:
I've set `Catkin_tools: Merged Compile Commands JSON Path` to `${workspaceFolder}/compile_commands.json`, 
and confirmed that it is also set in `settings.json`.
```json
"catkin_tools.mergedCompileCommandsJsonPath": "${workspaceFolder}/compile_commands.json"
```
But when I do `catkin clean` and `catkin build`, no file is generated.

Also, if I try the `Reload / Merge compile commands...` command, this error appears.
![ss_vscode-catkin-tools_err](https://user-images.githubusercontent.com/78188579/153794458-e6e497eb-13e5-4591-ac4c-d8cc4fcb618e.jpg)

### Output of vocode->help->About
Version: 1.64.2 (user setup)
Commit: f80445acd5a3dadef24aa209168452a3d97cc326
Date: 2022-02-09T22:02:28.252Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.18362

### extension version
v3.3.6

### Additional information
- I'm ssh-ing in a Ubuntu20.04 LTS virtual machine.
- ROS version is Noetic.
- the vscode workspace root is catkin-tools's workspace root (has .catkin_tools folder).
- I've set  `-DCMAKE_EXPORT_COMPILE_COMMANDS=ON`, so indicidual `compile_commands.json` exists in `build` folder.

**Comment by betwo** [comment] 2022-02-14 09:20
Hi @SubaruArai, thanks for reaching out!
I'll have a look at reproducing this as soon as possible.

**Comment by betwo** [comment] 2022-02-14 23:33
Ok, so the issue seems to be that the catkin workspace detection does not work in your case and therefore returns `undefined`.
This also explains why the automatic creation of the merged json file is not perfomed.

I'll add a checks for undefined there, but that does not actually solve your problem.
To debug this, could you please take a look at [the output panel and the the console log in the developer tools panel ](https://github.com/betwo/vscode-catkin-tools/wiki/DebuggingInstalled) and see if any other issues have occurred before?

**Comment by SubaruArai** [comment] 2022-02-14 23:51
Thanks for the ultra fast reply! (wait, it should be midnight at Germany...)

Somehow, today when I tried, it just worked!
Although I don't think it contains any useful information, I'll send the console log.
Here's the log file:
[vscode-app-1644882110189.log](https://github.com/betwo/vscode-catkin-tools/files/8064684/vscode-app-1644882110189.log)

And here's the output log (not from the dev tools panel)
```
Adding new workspace /home/username/catkin_ws
Reload catkin_ws
Done loading folder catkin_ws / /home/username/catkin_ws
Initializing test adapter for workspace /home/username/catkin_ws
Loading tests
```
Yesterday when I tried, there was no output log at all.

So, issue solved, I think...?
I'll close this issue, but if I encounter the same issue again, I won't forget to log!

**Closed as completed** 2022-02-14 23:51 UTC
Labels: bug

**Comment by betwo** [comment] 2022-02-15 10:36
> Thanks for the ultra fast reply! (wait, it should be midnight at Germany...)

You're welcome. Yeah, it got kind of late yesterday :smile: 

> Somehow, today when I tried, it just worked!
Although I don't think it contains any useful information, I'll send the console log.
...
Yesterday when I tried, there was no output log at all.

I think the issue then might be the extension startup. We have seen this a few times in the past and I'm currently working on stabilizing that via integration tests.

> So, issue solved, I think...?
I'll close this issue, but if I encounter the same issue again, I won't forget to log!

That would be great, if a log is then available at all.

Cheers
